export const colors = {
    background: '#F7F5FA',
    surface: '#FFFFFF',
    primary: '#7C5CBF',
    primaryLight: '#EDE7F6',
    primaryDark: '#5A3F94',
    accent: '#9B7ED8',
    success: '#00A870',
    sprout: '#2DB87A',
    /** Figma 온보딩 새싹 원 배경 */
    sproutTint: '#E8F7F0',
    cauldron: '#4A3B6B',
    textPrimary: '#191F28',
    textSecondary: '#6B7684',
    border: '#E5E8EB',
    heroTint: '#EDE7F6',
    tabBar: '#FFFFFF',
    slotEmpty: '#F0ECF5',
    slotFilled: '#DDD0F0',
} as const;
