/* eslint-disable */
// This file is auto-generated by @granite-js/react-native. DO NOT EDIT.

import { Route as _IndexRoute } from '../pages/';
import { Route as _LoginRoute } from '../pages/login';
import { Route as _OnboardingRoute } from '../pages/onboarding/';
import { Route as _OnboardingPractitionerRoute } from '../pages/onboarding/practitioner';
import { Route as _OnboardingExperienceRoute } from '../pages/onboarding/experience';
import { Route as _OnboardingInterestRoute } from '../pages/onboarding/interest';
import { Route as _MissionsRoute } from '../pages/missions/';
import { Route as _MissionDetailRoute } from '../pages/missions/[id]';
import { Route as _MissionVerifyRoute } from '../pages/missions/[id]/verify';
import { Route as _MissionResultRoute } from '../pages/missions/[id]/result';
import { Route as _ShopRoute } from '../pages/shop/';
import { Route as _ShopSelectRoute } from '../pages/shop/select';
import { Route as _ProfileRoute } from '../pages/profile/';

type MissionDetailParams = { id: string };

declare module '@granite-js/react-native' {
  interface RegisterScreenInput {
    '/': (typeof _IndexRoute)['_inputType'];
    '/login': (typeof _LoginRoute)['_inputType'];
    '/onboarding': (typeof _OnboardingRoute)['_inputType'];
    '/onboarding/practitioner': (typeof _OnboardingPractitionerRoute)['_inputType'];
    '/onboarding/experience': (typeof _OnboardingExperienceRoute)['_inputType'];
    '/onboarding/interest': (typeof _OnboardingInterestRoute)['_inputType'];
    '/missions': (typeof _MissionsRoute)['_inputType'];
    '/missions/:id': MissionDetailParams;
    '/missions/:id/verify': MissionDetailParams;
    '/missions/:id/result': MissionDetailParams;
    '/shop': (typeof _ShopRoute)['_inputType'];
    '/shop/select': (typeof _ShopSelectRoute)['_inputType'];
    '/profile': (typeof _ProfileRoute)['_inputType'];
  }

  interface RegisterScreen {
    '/': (typeof _IndexRoute)['_outputType'];
    '/login': (typeof _LoginRoute)['_outputType'];
    '/onboarding': (typeof _OnboardingRoute)['_outputType'];
    '/onboarding/practitioner': (typeof _OnboardingPractitionerRoute)['_outputType'];
    '/onboarding/experience': (typeof _OnboardingExperienceRoute)['_outputType'];
    '/onboarding/interest': (typeof _OnboardingInterestRoute)['_outputType'];
    '/missions': (typeof _MissionsRoute)['_outputType'];
    '/missions/:id': MissionDetailParams;
    '/missions/:id/verify': MissionDetailParams;
    '/missions/:id/result': MissionDetailParams;
    '/shop': (typeof _ShopRoute)['_outputType'];
    '/shop/select': (typeof _ShopSelectRoute)['_outputType'];
    '/profile': (typeof _ProfileRoute)['_outputType'];
  }
}
