/* eslint-disable */
// This file is auto-generated by @granite-js/react-native. DO NOT EDIT.
import { Route as _IndexRoute } from '../pages/';
import { Route as _LoginRoute } from '../pages/login';
import { Route as _MissionsIdRoute } from '../pages/missions/[id]';
import { Route as _MissionsRoute } from '../pages/missions';
import { Route as _OnboardingRoute } from '../pages/onboarding';
import { Route as _OnboardingTeamRoute } from '../pages/onboarding/team';
import { Route as _ProfileRoute } from '../pages/profile';
import { Route as _RankingRoute } from '../pages/ranking';
import { Route as _TeamRoute } from '../pages/team';

declare module '@granite-js/react-native' {
  interface RegisterScreenInput {
    '/': (typeof _IndexRoute)['_inputType'];
    '/login': (typeof _LoginRoute)['_inputType'];
    '/missions/[id]': (typeof _MissionsIdRoute)['_inputType'];
    '/missions': (typeof _MissionsRoute)['_inputType'];
    '/onboarding': (typeof _OnboardingRoute)['_inputType'];
    '/onboarding/team': (typeof _OnboardingTeamRoute)['_inputType'];
    '/profile': (typeof _ProfileRoute)['_inputType'];
    '/ranking': (typeof _RankingRoute)['_inputType'];
    '/team': (typeof _TeamRoute)['_inputType'];
  }

  interface RegisterScreen {
    '/': (typeof _IndexRoute)['_outputType'];
    '/login': (typeof _LoginRoute)['_outputType'];
    '/missions/[id]': (typeof _MissionsIdRoute)['_outputType'];
    '/missions': (typeof _MissionsRoute)['_outputType'];
    '/onboarding': (typeof _OnboardingRoute)['_outputType'];
    '/onboarding/team': (typeof _OnboardingTeamRoute)['_outputType'];
    '/profile': (typeof _ProfileRoute)['_outputType'];
    '/ranking': (typeof _RankingRoute)['_outputType'];
    '/team': (typeof _TeamRoute)['_outputType'];
  }
}
