/* eslint-disable */
// This file is auto-generated by @granite-js/react-native. DO NOT EDIT.
import { Route as _GachaRoute } from '../pages/gacha';
import { Route as _IndexRoute } from '../pages/';
import { Route as _IngredientsRoute } from '../pages/ingredients';
import { Route as _LoginRoute } from '../pages/login';
import { Route as _MissionsIdResultRoute } from '../pages/missions/[id]/result';
import { Route as _MissionsIdVerifyRoute } from '../pages/missions/[id]/verify';
import { Route as _MissionsIdRoute } from '../pages/missions/[id]';
import { Route as _MissionsRoute } from '../pages/missions';
import { Route as _OnboardingRoute } from '../pages/onboarding';
import { Route as _OnboardingShopRoute } from '../pages/onboarding/shop';
import { Route as _ProfileRoute } from '../pages/profile';
import { Route as _RecipesRoute } from '../pages/recipes';
import { Route as _ShopRoute } from '../pages/shop';
import { Route as _ShopSelectRoute } from '../pages/shop/select';
import { Route as _SoupResultRoute } from '../pages/soup/result';

declare module '@granite-js/react-native' {
  interface RegisterScreenInput {
    '/gacha': (typeof _GachaRoute)['_inputType'];
    '/': (typeof _IndexRoute)['_inputType'];
    '/ingredients': (typeof _IngredientsRoute)['_inputType'];
    '/login': (typeof _LoginRoute)['_inputType'];
    '/missions/[id]/result': (typeof _MissionsIdResultRoute)['_inputType'];
    '/missions/[id]/verify': (typeof _MissionsIdVerifyRoute)['_inputType'];
    '/missions/[id]': (typeof _MissionsIdRoute)['_inputType'];
    '/missions': (typeof _MissionsRoute)['_inputType'];
    '/onboarding': (typeof _OnboardingRoute)['_inputType'];
    '/onboarding/shop': (typeof _OnboardingShopRoute)['_inputType'];
    '/profile': (typeof _ProfileRoute)['_inputType'];
    '/recipes': (typeof _RecipesRoute)['_inputType'];
    '/shop': (typeof _ShopRoute)['_inputType'];
    '/shop/select': (typeof _ShopSelectRoute)['_inputType'];
    '/soup/result': (typeof _SoupResultRoute)['_inputType'];
  }

  interface RegisterScreen {
    '/gacha': (typeof _GachaRoute)['_outputType'];
    '/': (typeof _IndexRoute)['_outputType'];
    '/ingredients': (typeof _IngredientsRoute)['_outputType'];
    '/login': (typeof _LoginRoute)['_outputType'];
    '/missions/[id]/result': (typeof _MissionsIdResultRoute)['_outputType'];
    '/missions/[id]/verify': (typeof _MissionsIdVerifyRoute)['_outputType'];
    '/missions/[id]': (typeof _MissionsIdRoute)['_outputType'];
    '/missions': (typeof _MissionsRoute)['_outputType'];
    '/onboarding': (typeof _OnboardingRoute)['_outputType'];
    '/onboarding/shop': (typeof _OnboardingShopRoute)['_outputType'];
    '/profile': (typeof _ProfileRoute)['_outputType'];
    '/recipes': (typeof _RecipesRoute)['_outputType'];
    '/shop': (typeof _ShopRoute)['_outputType'];
    '/shop/select': (typeof _ShopSelectRoute)['_outputType'];
    '/soup/result': (typeof _SoupResultRoute)['_outputType'];
  }
}
