import type { AppUserState } from './types';
import { ECO_JAM_STARTING_BALANCE } from '../../shared/constants/ecoJamPolicy';
import { DEFAULT_AVATAR_ID } from '../../shared/constants/avatarOptions';

export const DEFAULT_USER_STATE: AppUserState = {
    userId: null,
    deviceId: null,
    onboardingCompleted: false,
    nickname: '',
    avatarId: DEFAULT_AVATAR_ID,
    phoneMasked: null,
    phoneNumber: null,
    almangPayoutConsent: 'declined',
    almangConsentAt: null,
    privacyConsentAt: null,
    locationConsent: null,
    locationConsentAt: null,
    cameraConsent: null,
    cameraConsentAt: null,
    shopId: null,
    lastCheckInDate: null,
    checkInDates: [],
    weeklyMissionDone: 0,
    weeklyMissionTotal: 6,
    totalPoints: 0,
    ecoJam: ECO_JAM_STARTING_BALANCE,
    totalCo2ReductionGrams: 0,
    ingredientInventory: {
        tomato: 1,
        onion: 1,
        carrot: 1,
        mushroom: 1,
        cabbage: 1,
    },
    completedRecipeIds: [],
    unlockedRecipeIds: [],
    lastSoupSession: null,
    missionProgress: {},
    ecoJamLedger: [],
    almangPointsLedger: [],
    gachaHistory: [],
    pendingRealRewards: [],
    lastShareRewardDate: null,
    hiddenTodayRecipePinId: null,
};
